baseURL = "http://localhost"
title = "WTFender"
theme = "soho"
languageCode = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true

pluralizeListTitles = false

[params]
  author = "WTFender"
  themeColor = "#03a9f4"


#customCss = ["css/blog.css"]
#customJs = ["js/blog.js"]

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/WTFender"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/WTFender"

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/michaelmcintyre5/"

[menu]

  [[menu.main]]
  name = "Archive"
  weight = 100
  identifier = "archive"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 300
  url = "/about/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4