baseURL = "http://localhost"
title = "WTFender"
theme = "soho"
languageCode = "en"
enableInlineShortcodes = true
summarylength = 100
enableEmoji = true
disqusShortname = "wtfender"
pluralizeListTitles = false

[params]
  author = "WTFender"
  themeColor = "#03a9f4"
  profilePicture = "img/profile.jpg"

  customCss = ["css/wtfender.css"]
  #customJs = ["js/blog.js"]

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/WTFender"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/WTFender"

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/michaelmcintyre5/"

[menu]

  [[menu.main]]
  name = "Tags"
  weight = 10
  identifier = "tags"
  url = "/tags/"

  [[menu.main]]
  name = "Archive"
  identifier = "posts"
  weight = 100
  url = "/posts/"

[taxonomies]
  tag = "tags"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  noClasses = true
  style = "pygments"
  tabWidth = 4

[blackfriday]
  extensions = [
    "hardLineBreak"
  ]