baseurl: 'https://blog.wtfender.com/'
languageCode: en-us
theme: stack
title: WTFender
copyright: WTFender
enableEmoji: true

# Theme i18n support
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
hasCJKLanguage: false

services:
    disqus:
        shortname: wtfender
    googleAnalytics:
        id: "GOOGLE_TAG"

pagination:
    pagerSize: 7

permalinks:
    post: /posts/:slug/
    page: /:slug/

params:
    mainSections:
        - posts
    featuredImageField: image
    rssFullContent: true
    favicon: /img/favicon/favicon.ico

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🔧
        subtitle: For nerds
        avatar:
            enabled: false
            local: true
            src: img/profile.jpg

    article:
        math: false
        toc: true
        readingTime: true
        lastUpdated: false
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: disqus

    widgets:
        homepage:
            - type: markdown-text
              params:
                  title: "Side Quests"
                  text: |
                      <div style="border-bottom: 1px solid rgba(255,255,255,0.1); padding-bottom: 8px; margin-bottom: 5px;">
                        <div style="display: flex; justify-content: space-between; align-items: center;">
                          <div style="flex: 1; text-align: left; margin-right: 10px;">
                            <a href="https://github.com/WTFender/aws-sso-extender" target="_blank" style="color: inherit; text-decoration: none;">
                              <strong>aws-sso-extender</strong>
                            </a>
                          </div>
                          <div style="flex: 0 0 80px; font-size: 14px; text-align: right;">
                            <svg width="12" height="12" fill="#F4C842" viewBox="0 0 16 16" style="vertical-align: middle; margin-right: 2px;">
                              <path d="M8 .25a.75.75 0 0 1 .673.418l1.882 3.815 4.21.612a.75.75 0 0 1 .416 1.279l-3.046 2.97.719 4.192a.75.75 0 0 1-1.088.791L8 12.347l-3.766 1.98a.75.75 0 0 1-1.088-.79l.72-4.194L.818 6.374a.75.75 0 0 1 .416-1.28l4.21-.611L7.327.668A.75.75 0 0 1 8 .25Z"/>
                            </svg>
                            78 
                            <svg width="12" height="12" fill="#23B0FF" viewBox="0 0 16 16" style="vertical-align: middle; margin: 0 2px;">
                              <path d="M5 5.372v.878c0 .414.336.75.75.75h4.5a.75.75 0 0 0 .75-.75v-.878a2.25 2.25 0 1 1 1.5 0v.878a2.25 2.25 0 0 1-2.25 2.25h-1.5v2.128a2.251 2.251 0 1 1-1.5 0V8.5h-1.5A2.25 2.25 0 0 1 3.5 6.25v-.878a2.25 2.25 0 1 1 1.5 0ZM5 3.25a.75.75 0 1 0-1.5 0 .75.75 0 0 0 1.5 0Zm6.75.75a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Zm-3 8.75a.75.75 0 1 0-1.5 0 .75.75 0 0 0 1.5 0Z"/>
                            </svg>
                            19
                          </div>
                        </div>
                        <div style="padding: 0 8px;">
                          <small style="opacity: 0.8; line-height: 1.1; text-align: left; display: block;">Browser extension for customizing AWS SSO and the AWS console.</small>
                        </div>
                      </div>

                      <div style="border-bottom: 1px solid rgba(255,255,255,0.1); padding-bottom: 8px; margin-bottom: 5px;">
                        <div style="display: flex; justify-content: space-between; align-items: center;">
                          <div style="flex: 1; text-align: left; margin-right: 10px;">
                            <a href="https://github.com/WTFender/csgobs" target="_blank" style="color: inherit; text-decoration: none;">
                              <strong>csgobs</strong>
                            </a>
                          </div>
                          <div style="flex: 0 0 80px; font-size: 14px; text-align: right;">
                            <svg width="12" height="12" fill="#F4C842" viewBox="0 0 16 16" style="vertical-align: middle; margin-right: 2px;">
                              <path d="M8 .25a.75.75 0 0 1 .673.418l1.882 3.815 4.21.612a.75.75 0 0 1 .416 1.279l-3.046 2.97.719 4.192a.75.75 0 0 1-1.088.791L8 12.347l-3.766 1.98a.75.75 0 0 1-1.088-.79l.72-4.194L.818 6.374a.75.75 0 0 1 .416-1.28l4.21-.611L7.327.668A.75.75 0 0 1 8 .25Z"/>
                            </svg>
                            7 
                            <svg width="12" height="12" fill="#23B0FF" viewBox="0 0 16 16" style="vertical-align: middle; margin: 0 2px;">
                              <path d="M5 5.372v.878c0 .414.336.75.75.75h4.5a.75.75 0 0 0 .75-.75v-.878a2.25 2.25 0 1 1 1.5 0v.878a2.25 2.25 0 0 1-2.25 2.25h-1.5v2.128a2.251 2.251 0 1 1-1.5 0V8.5h-1.5A2.25 2.25 0 0 1 3.5 6.25v-.878a2.25 2.25 0 1 1 1.5 0ZM5 3.25a.75.75 0 1 0-1.5 0 .75.75 0 0 0 1.5 0Zm6.75.75a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Zm-3 8.75a.75.75 0 1 0-1.5 0 .75.75 0 0 0 1.5 0Z"/>
                            </svg>
                            0
                          </div>
                        </div>
                        <div style="padding: 0 8px;">
                          <small style="opacity: 0.8; line-height: 1.1; text-align: left; display: block;">CS:GO OBS integration tool for streamers and content creators.</small>
                        </div>
                      </div>
                      
                      <div style="border-bottom: 1px solid rgba(255,255,255,0.1); padding-bottom: 8px; margin-bottom: 5px;">
                        <div style="display: flex; justify-content: space-between; align-items: center;">
                          <div style="flex: 1; text-align: left; margin-right: 10px;">
                            <a href="https://github.com/WTFender/aws-saml-keys" target="_blank" style="color: inherit; text-decoration: none;">
                              <strong>aws-saml-keys</strong>
                            </a>
                          </div>
                          <div style="flex: 0 0 80px; font-size: 14px; text-align: right;">
                            <svg width="12" height="12" fill="#F4C842" viewBox="0 0 16 16" style="vertical-align: middle; margin-right: 2px;">
                              <path d="M8 .25a.75.75 0 0 1 .673.418l1.882 3.815 4.21.612a.75.75 0 0 1 .416 1.279l-3.046 2.97.719 4.192a.75.75 0 0 1-1.088.791L8 12.347l-3.766 1.98a.75.75 0 0 1-1.088-.79l.72-4.194L.818 6.374a.75.75 0 0 1 .416-1.28l4.21-.611L7.327.668A.75.75 0 0 1 8 .25Z"/>
                            </svg>
                            1 
                            <svg width="12" height="12" fill="#23B0FF" viewBox="0 0 16 16" style="vertical-align: middle; margin: 0 2px;">
                              <path d="M5 5.372v.878c0 .414.336.75.75.75h4.5a.75.75 0 0 0 .75-.75v-.878a2.25 2.25 0 1 1 1.5 0v.878a2.25 2.25 0 0 1-2.25 2.25h-1.5v2.128a2.251 2.251 0 1 1-1.5 0V8.5h-1.5A2.25 2.25 0 0 1 3.5 6.25v-.878a2.25 2.25 0 1 1 1.5 0ZM5 3.25a.75.75 0 1 0-1.5 0 .75.75 0 0 0 1.5 0Zm6.75.75a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Zm-3 8.75a.75.75 0 1 0-1.5 0 .75.75 0 0 0 1.5 0Z"/>
                            </svg>
                            0
                          </div>
                        </div>
                        <div style="padding: 0 8px;">
                          <small style="opacity: 0.8; line-height: 1.1; text-align: left; display: block;">Tool for managing AWS credentials through SAML authentication.</small>
                        </div>
                      </div>
                      
                      <div style="padding-bottom: 8px;">
                        <div style="display: flex; justify-content: space-between; align-items: center;">
                          <div style="flex: 1; text-align: left; margin-right: 10px;">
                            <a href="https://github.com/WTFender/wpscan-action" target="_blank" style="color: inherit; text-decoration: none;">
                              <strong>wpscan-action</strong>
                            </a>
                          </div>
                          <div style="flex: 0 0 80px; font-size: 14px; text-align: right;">
                            <svg width="12" height="12" fill="#F4C842" viewBox="0 0 16 16" style="vertical-align: middle; margin-right: 2px;">
                              <path d="M8 .25a.75.75 0 0 1 .673.418l1.882 3.815 4.21.612a.75.75 0 0 1 .416 1.279l-3.046 2.97.719 4.192a.75.75 0 0 1-1.088.791L8 12.347l-3.766 1.98a.75.75 0 0 1-1.088-.79l.72-4.194L.818 6.374a.75.75 0 0 1 .416-1.28l4.21-.611L7.327.668A.75.75 0 0 1 8 .25Z"/>
                            </svg>
                            3 
                            <svg width="12" height="12" fill="#23B0FF" viewBox="0 0 16 16" style="vertical-align: middle; margin: 0 2px;">
                              <path d="M5 5.372v.878c0 .414.336.75.75.75h4.5a.75.75 0 0 0 .75-.75v-.878a2.25 2.25 0 1 1 1.5 0v.878a2.25 2.25 0 0 1-2.25 2.25h-1.5v2.128a2.251 2.251 0 1 1-1.5 0V8.5h-1.5A2.25 2.25 0 0 1 3.5 6.25v-.878a2.25 2.25 0 1 1 1.5 0ZM5 3.25a.75.75 0 1 0-1.5 0 .75.75 0 0 0 1.5 0Zm6.75.75a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Zm-3 8.75a.75.75 0 1 0-1.5 0 .75.75 0 0 0 1.5 0Z"/>
                            </svg>
                            7
                          </div>
                        </div>
                        <div style="padding: 0 8px;">
                          <small style="opacity: 0.8; line-height: 1.1; text-align: left; display: block;">GitHub Action for automated WordPress vulnerability scanning using WPScan.</small>
                        </div>
                      </div>
            - type: tag-cloud
              params:
                  limit: 50
        page:
            - type: toc

    opengraph:
        twitter:
            site: WTFender
            card: summary_large_image

    colorScheme:
        toggle: false
        default: dark

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

languages:
  en:
    languageName: English
    title: WTFender
    weight: 1
    params:
        sidebar:
            subtitle: For nerds

### Custom menu
menu:
    main:
        - identifier: about
          name: About
          url: /about/
          weight: 30
          params:
              icon: user

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/WTFender
          params:
              icon: brand-github
        - identifier: twitter
          name: Twitter
          url: https://x.com/WTFender
          params:
              icon: brand-twitter

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

markup:
    goldmark:
        renderer:
            unsafe: true
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: false
        lineNumbersInTable: true
        tabWidth: 4