name: Upload S3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      DISTRIBUTION_ID: E361J0JROY98AI
      AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/awstoken
      AWS_REGION: us-west-2
      AWS_S3_BUCKET: blog.wtfender.com
      SOURCE_DIR: 'public'
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set Environment Variables
      run: echo "REPO_NAME=${GITHUB_REPOSITORY#*\/}" >> $GITHUB_ENV
    - name: Get AWS Credentials Using OIDC
      run: |
        curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sigstore" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-region: ${{ env.AWS_REGION }}
        web-identity-token-file: ${{ env.AWS_WEB_IDENTITY_TOKEN_FILE }}
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        role-duration-seconds: 1800
        role-session-name: ${{ env.REPO_NAME }}-github-action
    - name: AWS Get Caller Identity
      run: aws sts get-caller-identity
    - name: Test
      run: aws s3 ls

    - name: Update Config
      run: |
        sed -i 's/http:\/\/localhost/https:\/\/blog.wtfender.com/g' config.toml
        sed -i 's/GOOGLE_TAG/G-FVQ5DMTCDK/g' config.toml

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: latest

    - name: Hugo Build
      run: hugo -D

    - name: S3 Upload
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete

    - name: Refresh CloudFront
      uses: awact/cloudfront-action@master


