name: Upload S3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      DISTRIBUTION_ID: E361J0JROY98AI
      AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/awstoken
      AWS_REGION: us-west-2
      AWS_S3_BUCKET: blog.wtfender.com
      SOURCE_DIR: 'public'
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Creds
      run: |
          export AWS_ROLE_ARN=arn:aws:iam::391785637824:role/github-blog-deploy-Role-1HNCJGO6Z14S9
          export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/awscreds
          export AWS_DEFAULT_REGION=us-west-2
          echo AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE >> $GITHUB_ENV
          echo AWS_ROLE_ARN=$AWS_ROLE_ARN >> $GITHUB_ENV
          echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $GITHUB_ENV
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
          aws sts get-caller-identity

    - name: Update Config
      run: |
        sed -i 's/http:\/\/localhost/https:\/\/blog.wtfender.com/g' config.toml
        sed -i 's/GOOGLE_TAG/G-FVQ5DMTCDK/g' config.toml

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: latest

    - name: Hugo Build
      run: |
        hugo -D
        ls -lha public

    - name: S3 Upload
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete

    - name: Refresh CloudFront
      uses: awact/cloudfront-action@master


