name: Upload S3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DISTRIBUTION_ID: E361J0JROY98AI
      AWS_S3_BUCKET: blog.wtfender.com
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-west-2'
      SOURCE_DIR: 'public'
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Update Config
      run: |
        sed -i 's/http:\/\/localhost/https:\/\/blog.wtfender.com/g' config.toml
        sed -i 's/GOOGLE_TAG/G-FVQ5DMTCDK/g' config.toml

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: latest

    - name: Hugo Build
      run: hugo -D

    - name: S3 Upload
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete

    - name: Refresh CloudFront
      uses: awact/cloudfront-action@master


