name: Upload S3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-west-2
      AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/awstoken
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}      
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Setup Creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: $AWS_ROLE_ARN
        role-session-name: github-actions
        aws-region: us-west-2

    - name: Update Config
      run: |
        sed -i 's/http:\/\/localhost/https:\/\/blog.wtfender.com/g' config.yaml
        sed -i 's/GOOGLE_TAG/${{secrets.GOOGLE_TAG}}/g' config.yaml

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: latest

    - name: Hugo Build
      run: hugo -d public

    - name: S3 Upload
      run: aws s3 sync public s3://$AWS_S3_BUCKET --acl public-read --follow-symlinks --delete

    - name: Refresh CloudFront
      run: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
