name: Upload S3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      DISTRIBUTION_ID: E361J0JROY98AI
      AWS_S3_BUCKET: blog.wtfender.com
      SOURCE_DIR: 'public'
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Credentials
      run: |
        OIDC_TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=o6s" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN")
        JWT=$(echo $OIDC_TOKEN | jq -j '.value')
        aws assume-role-with-web-identity --role-arn arn:aws:iam::391785637824:role/github-blog-deploy-Role-1HNCJGO6Z14S9 --role-session-name GitHubActions --web-identity-token $JWT

    - name: Test
      run: aws s3 ls

    - name: Update Config
      run: |
        sed -i 's/http:\/\/localhost/https:\/\/blog.wtfender.com/g' config.toml
        sed -i 's/GOOGLE_TAG/G-FVQ5DMTCDK/g' config.toml

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: latest

    - name: Hugo Build
      run: hugo -D

    - name: S3 Upload
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete

    - name: Refresh CloudFront
      uses: awact/cloudfront-action@master


