name: Setup AWS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@master
  
    - name: Download Artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: deploy.yml
        workflow_conclusion: success
        branch: main
        name: public.tar.gz
        if_no_artifact_found: fail
